-- =============================================================
--  CRESCENDO 2026 — Supabase setup
--  Project: crescendo-2026   (NOT Ballet Ball)
--  Run once, top to bottom, in the Supabase SQL Editor.
--
--  BEFORE RUNNING: replace both occurrences of
--    '00000000-0000-0000-0000-000000000000'
--  with your admin user's UUID (Authentication > Users).
-- =============================================================


-- -------------------------------------------------------------
-- 1. TABLE
-- -------------------------------------------------------------
-- Column names match normaliseRow() in admin_crescendo.html exactly.
--
-- table_number is TEXT, not INT — rosters contain values like "12A".
--
-- NO unique constraint on email. Verified against current behavior:
-- two people sharing one address upload cleanly and both are returned
-- and checked in by a single lookup. Uniqueness would break that.

create table public.registrations (
  id             bigint generated by default as identity primary key,
  first_name     text        not null default '',
  last_name      text        not null default '',
  email          text        not null,
  table_number   text        not null default '',
  room           text        not null default '',
  checked_in     boolean     not null default false,
  check_in_time  timestamptz,
  checkin_method text,

  -- Reject anything not already lowercase+trimmed. normaliseRow() does
  -- this in JS on upload; this catches hand-typed Table Editor entries,
  -- which would otherwise be silently unfindable by the lookup functions.
  constraint registrations_email_normalised check (email = lower(btrim(email))),
  constraint registrations_email_notblank   check (length(email) > 0),

  -- 'self'      = email flow (guest or volunteer at the desk)
  -- 'volunteer' = reserved for the PIN-gated name search, added later
  constraint registrations_checkin_method check (
    checkin_method is null or checkin_method in ('self','volunteer')
  )
);

create index registrations_email_idx     on public.registrations (email);
create index registrations_last_name_idx on public.registrations (last_name);


-- -------------------------------------------------------------
-- 2. ROW LEVEL SECURITY
-- -------------------------------------------------------------

alter table public.registrations enable row level security;

-- Scoped to ONE user UUID, not to the 'authenticated' role at large.
-- If public signups are ever switched on by accident, a new account
-- matches no policy and receives nothing.
create policy "admin_full_access"
  on public.registrations
  for all
  to authenticated
  using      (auth.uid() = '00000000-0000-0000-0000-000000000000'::uuid)
  with check (auth.uid() = '00000000-0000-0000-0000-000000000000'::uuid);

-- Deliberately NO policy for anon. The guest page never touches the
-- table directly — it goes through the two functions in section 4.


-- -------------------------------------------------------------
-- 3. TABLE GRANTS
-- -------------------------------------------------------------
-- Required because "Automatically expose new tables" is OFF.

grant usage on schema public to anon, authenticated;

-- Admin needs all four: select (dashboard + export),
-- delete + insert (roster upload), update (headroom).
grant select, insert, update, delete on public.registrations to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- anon gets nothing on the table itself. Ever.
revoke all on public.registrations from anon;


-- -------------------------------------------------------------
-- 4. GUEST FUNCTIONS  (the only thing anon can reach)
-- -------------------------------------------------------------
-- SECURITY DEFINER: these run as owner and bypass RLS by design.
-- Email is the credential. No row IDs cross the wire, so the roster
-- cannot be enumerated by guessing sequential ids.
--
-- 'r.email = any(v_emails)' iterates rows, not the input array — so a
-- duplicated input address collapses to one result per person, matching
-- the existing records.filter() behavior exactly.


-- --- 4a. SEARCH step -----------------------------------------
-- Returns names and status ONLY. No table_number, no room.
-- A search on its own reveals nothing about seating.

create or replace function public.guest_lookup(p_emails text[])
returns table (
  first_name text,
  last_name  text,
  email      text,
  checked_in boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_emails text[];
begin
  if p_emails is null or array_length(p_emails, 1) is null
     or array_length(p_emails, 1) > 10 then
    raise exception 'Invalid request';
  end if;

  select array_agg(lower(btrim(e)))
    into v_emails
    from unnest(p_emails) as e
   where length(btrim(e)) > 0;

  return query
    select r.first_name, r.last_name, r.email, r.checked_in
      from public.registrations r
     where r.email = any (v_emails);
end;
$$;


-- --- 4b. CHECK-IN step ---------------------------------------
-- Takes the SAME email array the search took and re-matches it.
-- Nothing is trusted from the client between the two screens.
--
-- Returns table_number and room — this is where seating is revealed.
-- Already-checked-in guests come back with their ORIGINAL timestamp
-- rather than an error, so a returning guest just sees their table again.

create or replace function public.guest_checkin(p_emails text[])
returns table (
  first_name    text,
  last_name     text,
  email         text,
  table_number  text,
  room          text,
  checked_in    boolean,
  check_in_time timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_emails text[];
begin
  if p_emails is null or array_length(p_emails, 1) is null
     or array_length(p_emails, 1) > 10 then
    raise exception 'Invalid request';
  end if;

  select array_agg(lower(btrim(e)))
    into v_emails
    from unnest(p_emails) as e
   where length(btrim(e)) > 0;

  update public.registrations r
     set checked_in     = true,
         check_in_time  = now(),
         checkin_method = 'self'
   where r.email = any (v_emails)
     and r.checked_in = false;

  return query
    select r.first_name, r.last_name, r.email,
           r.table_number, r.room, r.checked_in, r.check_in_time
      from public.registrations r
     where r.email = any (v_emails);
end;
$$;


-- -------------------------------------------------------------
-- 5. FUNCTION GRANTS
-- -------------------------------------------------------------
-- Postgres grants EXECUTE to PUBLIC by default, so revoke first.

revoke all on function public.guest_lookup(text[])  from public;
revoke all on function public.guest_checkin(text[]) from public;

grant execute on function public.guest_lookup(text[])  to anon, authenticated;
grant execute on function public.guest_checkin(text[]) to anon, authenticated;


-- =============================================================
--  VERIFICATION — run each of these after the script above
-- =============================================================

-- (a) RLS on, exactly one policy:
--   select relrowsecurity from pg_class where relname = 'registrations';
--     expect: true
--   select policyname, roles, cmd from pg_policies
--    where tablename = 'registrations';
--     expect: one row -> admin_full_access | {authenticated} | ALL

-- (b) anon holds NO table privileges:
--   select privilege_type from information_schema.role_table_grants
--    where table_name = 'registrations' and grantee = 'anon';
--     expect: zero rows

-- (c) anon can execute exactly the two functions and nothing else:
--   select p.proname, has_function_privilege('anon', p.oid, 'execute') as anon_exec
--     from pg_proc p join pg_namespace n on n.oid = p.pronamespace
--    where n.nspname = 'public';
--     expect: guest_lookup true, guest_checkin true, all others false

-- (d) Shared-address behavior. Insert two people on one email,
--     confirm both come back, then clean up:
--   insert into public.registrations (first_name,last_name,email,table_number,room)
--   values ('Jane','Smith','jsmith@example.com','12','Kirkwood'),
--          ('John','Smith','jsmith@example.com','14','Rozzelle');
--   select * from public.guest_lookup(array['jsmith@example.com']);
--     expect: 2 rows, Jane and Jane's status, John and John's status
--   select * from public.guest_lookup(array['jsmith@example.com','jsmith@example.com']);
--     expect: still 2 rows, not 4
--   select * from public.guest_checkin(array['jsmith@example.com']);
--     expect: 2 rows with table 12/Kirkwood and 14/Rozzelle
--   delete from public.registrations where email = 'jsmith@example.com';
