-- ============================================================================
-- Crescendo 2026 Check-In — Complete Database Setup
--
-- Generated from the live crescendo-2026 database on 2026-07-25.
-- Function bodies, column definitions, constraints, indexes, and policies were
-- all read out of the catalog with pg_get_functiondef / information_schema —
-- they are verbatim, not reconstructed.
--
-- Supersedes crescendo_supabase_setup.sql (handoff #2), which predates the
-- volunteer path and will NOT produce a working database.
--
-- PURPOSE: rebuild from scratch after a total loss. Running this against a
-- database that already has data will not destroy it (creates are guarded),
-- but it is not a migration script.
--
-- BEFORE RUNNING, replace two placeholders:
--   <ADMIN-UUID>    the auth.users UUID that owns the admin dashboard
--                   (currently e2f21c69-b80b-431a-b3ae-e77b32f4aa60)
--   <VOLUNTEER-PIN> the shared volunteer PIN, 8+ characters
--
-- ORDER MATTERS. Run top to bottom in one pass.
-- ============================================================================


-- ============================================================================
-- SECTION 1 — EXTENSIONS
-- ============================================================================

create extension if not exists pgcrypto with schema extensions;


-- ============================================================================
-- SECTION 2 — TABLES
-- ============================================================================

-- ─── registrations ──────────────────────────────────────────────────────────
-- Column names match normaliseRow() in admin_crescendo.html exactly.
-- Do not rename.
--
-- email is NOT unique and NOT constrained to be non-empty:
--   * couples registering once share a single address; both must check in from
--     one lookup, and a unique constraint would hard-fail the whole batch insert
--   * guests who never gave an address have a blank email and are checked in by
--     row id through the volunteer page
--
-- table_number is TEXT, not INT — rosters contain values like "12A".

create table if not exists public.registrations (
  id             bigint generated by default as identity primary key,
  first_name     text not null default ''::text,
  last_name      text not null default ''::text,
  email          text not null,
  table_number   text not null default ''::text,
  room           text not null default ''::text,
  checked_in     boolean not null default false,
  check_in_time  timestamptz,
  checkin_method text
);

do $$
begin
  if not exists (select 1 from pg_constraint
                  where conname = 'registrations_email_normalised') then
    alter table public.registrations
      add constraint registrations_email_normalised
      check (email = lower(btrim(email)));
  end if;

  if not exists (select 1 from pg_constraint
                  where conname = 'registrations_checkin_method') then
    alter table public.registrations
      add constraint registrations_checkin_method
      check (checkin_method is null
             or checkin_method = any (array['self'::text, 'volunteer'::text]));
  end if;
end $$;

-- NOTE: a constraint named registrations_email_notblank (length(email) > 0)
-- existed and was DROPPED deliberately. Do not re-add it — it blocks the
-- emailless guests the volunteer page is built to handle.

create index if not exists registrations_email_idx
  on public.registrations using btree (email);
create index if not exists registrations_last_name_idx
  on public.registrations using btree (last_name);


-- ─── app_settings ───────────────────────────────────────────────────────────
-- Holds the bcrypt hash of the volunteer PIN under key 'volunteer_pin_hash'.
-- The hash lives here rather than inside a function body because pg_proc is
-- readable by anon.

create table if not exists public.app_settings (
  key        text primary key,
  value      text not null,
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- SECTION 3 — ROW LEVEL SECURITY
--
-- Policies are scoped to a single admin UUID rather than the `authenticated`
-- role at large, so a stray account matches no policy and gets nothing.
-- ============================================================================

alter table public.registrations enable row level security;
alter table public.app_settings  enable row level security;

drop policy if exists "admin_full_access" on public.registrations;
create policy "admin_full_access" on public.registrations
  for all to authenticated
  using      (auth.uid() = '<ADMIN-UUID>'::uuid)
  with check (auth.uid() = '<ADMIN-UUID>'::uuid);

drop policy if exists "admin_settings_access" on public.app_settings;
create policy "admin_settings_access" on public.app_settings
  for all to authenticated
  using      (auth.uid() = '<ADMIN-UUID>'::uuid)
  with check (auth.uid() = '<ADMIN-UUID>'::uuid);


-- ============================================================================
-- SECTION 4 — TABLE GRANTS
--
-- anon gets NOTHING on either table. Every guest and volunteer operation goes
-- through a SECURITY DEFINER function. This is the line that makes the roster
-- unreachable with the publishable key.
-- ============================================================================

revoke all on public.registrations from public, anon, authenticated;
revoke all on public.app_settings  from public, anon, authenticated;

grant select, insert, update, delete on public.registrations to authenticated;
grant select, insert, update, delete on public.app_settings  to authenticated;

grant usage on schema public to anon, authenticated;


-- ============================================================================
-- SECTION 5 — FUNCTIONS
--
-- All SECURITY DEFINER with search_path pinned. All cap array arguments at 10.
-- All raise the same opaque 'Invalid request' so a bad PIN and a malformed
-- call are indistinguishable from outside.
-- ============================================================================

-- ─── volunteer_pin_check ────────────────────────────────────────────────────
-- Returns a boolean and nothing else. Callable by anon so the PIN screen can
-- validate before searching.

CREATE OR REPLACE FUNCTION public.volunteer_pin_check(p_pin text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions', 'pg_temp'
AS $function$
declare
  v_hash text;
begin
  if p_pin is null or length(p_pin) = 0 then
    return false;
  end if;

  select value into v_hash
    from public.app_settings
   where key = 'volunteer_pin_hash';

  if v_hash is null then
    return false;
  end if;

  return extensions.crypt(p_pin, v_hash) = v_hash;
end;
$function$;


-- ─── guest_lookup ───────────────────────────────────────────────────────────
-- Guest page search. Returns names and status only — NO table_number or room.
-- A search on its own reveals nothing about seating.
-- Strips empty strings from the array, so a blank email can never match.

CREATE OR REPLACE FUNCTION public.guest_lookup(p_emails text[])
 RETURNS TABLE(first_name text, last_name text, email text, checked_in boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_emails text[];
begin
  if p_emails is null or array_length(p_emails, 1) is null
     or array_length(p_emails, 1) > 10 then
    raise exception 'Invalid request';
  end if;

  select array_agg(lower(btrim(e)))
    into v_emails
    from unnest(p_emails) as e
   where length(btrim(e)) > 0;

  return query
    select r.first_name, r.last_name, r.email, r.checked_in
      from public.registrations r
     where r.email = any (v_emails);
end;
$function$;


-- ─── guest_checkin ──────────────────────────────────────────────────────────
-- Guest self check-in. Re-matches the email array server-side, so no row ids
-- cross the wire and the roster cannot be enumerated by guessing ids.
-- The `and r.checked_in = false` guard makes re-check-in a no-op that preserves
-- the original check_in_time.

CREATE OR REPLACE FUNCTION public.guest_checkin(p_emails text[])
 RETURNS TABLE(first_name text, last_name text, email text, table_number text, room text, checked_in boolean, check_in_time timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_emails text[];
begin
  if p_emails is null or array_length(p_emails, 1) is null
     or array_length(p_emails, 1) > 10 then
    raise exception 'Invalid request';
  end if;

  select array_agg(lower(btrim(e)))
    into v_emails
    from unnest(p_emails) as e
   where length(btrim(e)) > 0;

  update public.registrations r
     set checked_in     = true,
         check_in_time  = now(),
         checkin_method = 'self'
   where r.email = any (v_emails)
     and r.checked_in = false;

  return query
    select r.first_name, r.last_name, r.email,
           r.table_number, r.room, r.checked_in, r.check_in_time
      from public.registrations r
     where r.email = any (v_emails);
end;
$function$;


-- ─── guest_lookup_by_name ───────────────────────────────────────────────────
-- Volunteer name search. PIN verified server-side on EVERY call — a gate in the
-- webpage alone would be bypassable by calling this directly with the
-- publishable key.
--
-- Returns id (needed to check in guests with no email) but NO table_number or
-- room, matching guest_lookup.
--
-- Requires a last name of 2+ characters and caps at 25 rows so the roster
-- cannot be dumped. Strips % _ \ so input cannot widen the match.

CREATE OR REPLACE FUNCTION public.guest_lookup_by_name(p_pin text, p_first text, p_last text)
 RETURNS TABLE(id bigint, first_name text, last_name text, email text, checked_in boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions', 'pg_temp'
AS $function$
declare
  v_first text := lower(btrim(coalesce(p_first, '')));
  v_last  text := lower(btrim(coalesce(p_last,  '')));
begin
  if not public.volunteer_pin_check(p_pin) then
    raise exception 'Invalid request';
  end if;

  v_first := regexp_replace(v_first, '[%_\\]', '', 'g');
  v_last  := regexp_replace(v_last,  '[%_\\]', '', 'g');

  if length(v_last) < 2 then
    raise exception 'Last name must be at least 2 characters';
  end if;

  return query
  select r.id,
         r.first_name,
         r.last_name,
         r.email,
         r.checked_in
    from public.registrations r
   where lower(btrim(r.last_name)) like v_last || '%'
     and (v_first = '' or lower(btrim(r.first_name)) like v_first || '%')
   order by r.last_name, r.first_name
   limit 25;
end;
$function$;


-- ─── guest_checkin_volunteer ────────────────────────────────────────────────
-- Volunteer check-in via the email path. Identical to guest_checkin except for
-- the PIN gate and checkin_method = 'volunteer'.

CREATE OR REPLACE FUNCTION public.guest_checkin_volunteer(p_pin text, p_emails text[])
 RETURNS TABLE(first_name text, last_name text, email text, table_number text, room text, checked_in boolean, check_in_time timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_emails text[];
begin
  if not public.volunteer_pin_check(p_pin) then
    raise exception 'Invalid request';
  end if;

  if p_emails is null or array_length(p_emails, 1) is null
     or array_length(p_emails, 1) > 10 then
    raise exception 'Invalid request';
  end if;

  select array_agg(lower(btrim(e)))
    into v_emails
    from unnest(p_emails) as e
   where length(btrim(e)) > 0;

  update public.registrations r
     set checked_in     = true,
         check_in_time  = now(),
         checkin_method = 'volunteer'
   where r.email = any (v_emails)
     and r.checked_in = false;

  return query
    select r.first_name, r.last_name, r.email,
           r.table_number, r.room, r.checked_in, r.check_in_time
      from public.registrations r
     where r.email = any (v_emails);
end;
$function$;


-- ─── guest_checkin_by_id ────────────────────────────────────────────────────
-- Volunteer check-in via the name path. Targets rows by id because a blank
-- email cannot identify anyone. Reaching an id already requires the PIN.

CREATE OR REPLACE FUNCTION public.guest_checkin_by_id(p_pin text, p_ids bigint[])
 RETURNS TABLE(id bigint, first_name text, last_name text, email text, table_number text, room text, checked_in boolean, check_in_time timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
begin
  if not public.volunteer_pin_check(p_pin) then
    raise exception 'Invalid request';
  end if;

  if p_ids is null or array_length(p_ids, 1) is null
     or array_length(p_ids, 1) > 10 then
    raise exception 'Invalid request';
  end if;

  update public.registrations r
     set checked_in     = true,
         check_in_time  = now(),
         checkin_method = 'volunteer'
   where r.id = any (p_ids)
     and r.checked_in = false;

  return query
    select r.id, r.first_name, r.last_name, r.email,
           r.table_number, r.room, r.checked_in, r.check_in_time
      from public.registrations r
     where r.id = any (p_ids);
end;
$function$;


-- ─── guest_set_email ────────────────────────────────────────────────────────
-- Captures an address a guest gives at the desk. Fills a BLANK only — never
-- overwrites an address already on file, so a typo cannot destroy good data.
-- Enforced here, not just in the UI.

CREATE OR REPLACE FUNCTION public.guest_set_email(p_pin text, p_id bigint, p_email text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_rows  int;
begin
  if not public.volunteer_pin_check(p_pin) then
    raise exception 'Invalid request';
  end if;

  -- Must look like an email. Nothing fancy, just a sanity check.
  if v_email = ''
     or position('@' in v_email) = 0
     or position('.' in split_part(v_email, '@', 2)) = 0
     or length(v_email) > 254 then
    raise exception 'Invalid request';
  end if;

  -- Only fills a blank. Never overwrites an address already on file.
  update public.registrations r
     set email = v_email
   where r.id = p_id
     and btrim(coalesce(r.email, '')) = '';

  get diagnostics v_rows = row_count;
  return v_rows > 0;
end;
$function$;


-- ============================================================================
-- SECTION 6 — FUNCTION GRANTS
--
-- BOTH anon AND authenticated. This is not optional and is not redundant.
--
-- All three pages share a browser origin, and supabase-js persists sessions per
-- origin. If anyone signs into the admin page, other pages in that browser can
-- send the admin JWT and be evaluated as `authenticated` rather than `anon`.
-- Granting only anon produces a 42501 that is extremely hard to diagnose,
-- because the catalog will show anon holding EXECUTE the whole time.
--
-- The client pages are also configured with persistSession:false to prevent
-- this, but the grants are the belt to that suspenders.
-- ============================================================================

revoke all on function public.volunteer_pin_check(text)              from public;
revoke all on function public.guest_lookup(text[])                   from public;
revoke all on function public.guest_checkin(text[])                  from public;
revoke all on function public.guest_lookup_by_name(text, text, text) from public;
revoke all on function public.guest_checkin_volunteer(text, text[])  from public;
revoke all on function public.guest_checkin_by_id(text, bigint[])    from public;
revoke all on function public.guest_set_email(text, bigint, text)    from public;

grant execute on function public.volunteer_pin_check(text)              to anon, authenticated;
grant execute on function public.guest_lookup(text[])                   to anon, authenticated;
grant execute on function public.guest_checkin(text[])                  to anon, authenticated;
grant execute on function public.guest_lookup_by_name(text, text, text) to anon, authenticated;
grant execute on function public.guest_checkin_volunteer(text, text[])  to anon, authenticated;
grant execute on function public.guest_checkin_by_id(text, bigint[])    to anon, authenticated;
grant execute on function public.guest_set_email(text, bigint, text)    to anon, authenticated;


-- ============================================================================
-- SECTION 7 — SET THE VOLUNTEER PIN
--
-- Re-run this statement alone to rotate the PIN. Nothing else references it.
-- The PIN itself is never stored, only a bcrypt hash — it cannot be read back.
-- Write it down.
-- ============================================================================

insert into public.app_settings (key, value)
values ('volunteer_pin_hash',
        extensions.crypt('<VOLUNTEER-PIN>', extensions.gen_salt('bf', 10)))
on conflict (key) do update
  set value = excluded.value,
      updated_at = now();


-- ============================================================================
-- SECTION 8 — VERIFICATION
-- Run each block and check the result before going live.
-- ============================================================================

-- (a) anon must have NO table privileges. Both rows must read NONE.
--     This is the line that proves the roster is unreachable with the
--     publishable key.
select 'registrations' as tbl,
       coalesce(nullif(string_agg(privilege_type, ', '), ''), 'NONE') as anon_privs
  from information_schema.role_table_grants
 where grantee = 'anon' and table_schema = 'public' and table_name = 'registrations'
union all
select 'app_settings',
       coalesce(nullif(string_agg(privilege_type, ', '), ''), 'NONE')
  from information_schema.role_table_grants
 where grantee = 'anon' and table_schema = 'public' and table_name = 'app_settings';

-- (b) Every function must be executable by BOTH roles. All seven rows true/true.
--     Checking only anon is what caused the 42501 incident in session #3.
select p.proname,
       has_function_privilege('anon', p.oid, 'EXECUTE')          as anon_ok,
       has_function_privilege('authenticated', p.oid, 'EXECUTE') as auth_ok
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
 where n.nspname = 'public'
   and p.proname in ('volunteer_pin_check', 'guest_lookup', 'guest_checkin',
                     'guest_lookup_by_name', 'guest_checkin_volunteer',
                     'guest_checkin_by_id', 'guest_set_email')
 order by 1;

-- (c) RLS on, one policy per table.
select tablename, policyname, cmd, roles
  from pg_policies
 where schemaname = 'public'
 order by tablename;

-- (d) PIN round-trip. Expect true then false.
--     Replace <VOLUNTEER-PIN> with the real PIN.
-- select public.volunteer_pin_check('<VOLUNTEER-PIN>') as should_be_true,
--        public.volunteer_pin_check('definitely-wrong') as should_be_false;

-- (e) Wrong PIN must RAISE, not return rows. Expect an error.
-- select * from public.guest_lookup_by_name('wrong-pin', '', 'smith');

-- (f) A blank email must be unreachable from the guest page. Both zero.
-- select 'blank' as attempt, count(*) from public.guest_lookup(array['']::text[])
-- union all
-- select 'space', count(*) from public.guest_lookup(array[' ']::text[]);


-- ============================================================================
-- SECTION 9 — POST-REBUILD CHECKLIST
--
--  1. Create the admin auth user (Authentication → Users → Add user, with
--     "Auto Confirm User" ticked), then put its UUID in Section 3 above and
--     re-run that section. Password reset by email does NOT work on the free
--     tier; set passwords directly with:
--
--       update auth.users
--          set encrypted_password = extensions.crypt('NEW-PASSWORD',
--                                                    extensions.gen_salt('bf')),
--              email_confirmed_at = coalesce(email_confirmed_at, now()),
--              updated_at = now()
--        where email = '<ADMIN-EMAIL>';
--
--  2. Disable public signups (Authentication → Sign In / Providers).
--  3. Put the project URL and publishable key into config.js.
--  4. Upload the roster through admin_crescendo.html. Upload REPLACES the
--     roster entirely: delete-all then insert with checked_in = false. This is
--     intended. Do not add a confirmation guard.
--  5. Run every block in Section 8.
-- ============================================================================
